### ISSUE TITLE
What analog for 'component' binding should we use now?

### ISSUE THREAD

**Issue by crawter** [ryansolid/ko-jsx#1]
Hello!

At the moment I'm choosing a new fast js framework to rewrite the frontend of my project (which was written on knockout.js)

In my search, I came across your project and I really liked it.

I have a question, how to dynamically change the components, in case when bindings (data-bind = "component: compName") no longer work?

Would you kindly advise me a router that is compatible with ko-jsx or another way to achieve this goal?

Thanks!

**Comment by ryansolid** [comment]
There are a couple options depending on how you want to package up (componentize your code). 
Essentially the pattern for dynamically inserting components is more like React where it's just an if statement essentially. 

```jsx
<div>{(
  routeName() === 'comp1' ? <Comp1 /> : <Comp2 />
)}</div>
````
This overly simplistic. Obviously you could do some sort of lookup for the Component. It's just javascript so no binding required. So a generic library like [Page.js](https://visionmedia.github.io/page.js/) could do the trick.  Essentially any routing solution that uses a callback function could set an observable/s that define the route and lookup the Component to instantiate. You can always assign a Component to a variable and render that variable as a tag.

```jsx
const Component = routes[routeName()]
<Component />
```
The biggest difference between the render trees is understanding how the library uses nested computed context. This is all part of the base library I wrote for rendering that I use here that isn't specific to ko-jsx, and I haven't done as good job explaining how it works here as my other libraries. In basic though each JSX expression is wrapped in a computed so dereferencing observables will cause the expression block to recalculate.

Using Web Components is what I actually use for my own stuff mostly. I wrote 2 libraries to help with this: [Component Register](https://github.com/ryansolid/component-register) which is a simple wrapper for creating Web Components and [WebComponent Router](https://github.com/ryansolid/webcomponent-router) which is a generic router that renders custom element tags.

I know I need some more concrete examples and documentation. I will put together a TodoMVC soon. However the library limited scope should work with most general solutions, but haven't really taken it that far yet.  Let me know if I can help clarify further.

**Comment by ryansolid** [comment]
I'd to like to add now the Control flow elements in the JSX compiler offer a pretty easy solution to this problem as well now. While not specific to ko-jsx, [this codepen](https://codepen.io/ryansolid/pen/OGMjzE?editors=1000) uses Solid also based on this renderer displaying how simple routing could work. createSignal === ko.observable essentially and then the rest just follows.
