### ISSUE TITLE
Example App?

### ISSUE THREAD

**Issue by DavidBernal** [ryansolid/ko-jsx#3]
Hi @ryansolid, have you a demo/boilerplate/example app in order to start a new project?

Configure all tools could be a little hard.

**Comment by ryansolid** [comment]
I wouldn't necessarily call this an app. But it has most of the configuration. Very simple setup with Parcel and Babel. https://codesandbox.io/s/knockout-jsx-counter-dqtc2. It's pretty similar with Webpack or Rollup.
